/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.DBModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import model.IModel;
import model.Kerdes;

/**
 *
 * @author nagyg
 */
public class Foablak extends javax.swing.JFrame {

    private IModel model;
    private Vector<Kerdes> kerdesek;
    private int szint;
    private Kerdes aktKerdes;

    public Foablak() throws SQLException {
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                sajatClose();
            }
        });
        setLocationRelativeTo(null);
        setTitle("Legyen Ön is milliomos!");

        String dbUser = "root";
        String dbPass = "1234";
        String dbURL = "jdbc:mysql://localhost:3306/loim";

        String[] listData = {"15. 40 000 000", "14. 20 000 000", "13. 10 000 000", "12. 5 000 000", "11. 3 000 000",
            "10. 1 500 000", "9. 800 000", "8. 500 000", "7. 300 000", "6. 200 000", "5. 100 000", "4. 50 000", "3. 25 000", "2. 10 000", "1. 5000"};

        lstNyeremenySzintek.setListData(listData);

        szint = 14;
 
        try {
            Connection conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            model = new DBModel(conn);
            kerdesek = model.getAllKerdes();
            lstNyeremenySzintek.setSelectedIndex(szint);
            kerdesFeltesz();

        } catch (SQLException ex) {
            hibaAblak(ex.toString());
        }
    }

    public void kerdesFeltesz() {
        Random veletlenKerdesKeszito = new Random();
        int veletlen = 0;
        veletlen = veletlenKerdesKeszito.nextInt(kerdesek.size());

        aktKerdes = kerdesek.get(veletlen);
        lbKerdes.setText(aktKerdes.getKerdes());

        btnValasz0.setText(aktKerdes.getValasz0());
        btnValasz1.setText(aktKerdes.getValasz1());
        btnValasz2.setText(aktKerdes.getValasz2());
        btnValasz3.setText(aktKerdes.getValasz3());
    }

    public void valaszVizsgal(int gomb) {
        if (aktKerdes.getHelyesValasz() == gomb) {
            kerdesFeltesz();
            szint = szint - 1;
            lstNyeremenySzintek.setSelectedIndex(szint);

        } else {
            Object[] valaszok = {"Igen", "Nem"};
            int valasz = JOptionPane.showOptionDialog(this, "Szeretnéd úrja kezdeni a játákot?", "Újra?",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, valaszok, valaszok[0]);
            if (valasz == JOptionPane.YES_OPTION) {
                szint = 14;
                lstNyeremenySzintek.setSelectedIndex(szint);
                kerdesFeltesz();
            } else {
                sajatClose();
            }
        }
    }

    public static void hibaAblak(String hiba) {
        JOptionPane.showMessageDialog(null, hiba, "Hiba történt",
                JOptionPane.ERROR_MESSAGE);
    }

    public void sajatClose() {
        if (model != null) {
            try {
                model.close();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.toString(), "Adatbázis hiba",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValasz0 = new javax.swing.JButton();
        btnValasz1 = new javax.swing.JButton();
        btnValasz2 = new javax.swing.JButton();
        btnValasz3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNyeremenySzintek = new javax.swing.JList<>();
        lbKerdes = new javax.swing.JLabel();
        lbVagoIstvanKep = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnValasz0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnValasz0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz0ActionPerformed(evt);
            }
        });

        btnValasz1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnValasz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz1ActionPerformed(evt);
            }
        });

        btnValasz2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnValasz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz2ActionPerformed(evt);
            }
        });

        btnValasz3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnValasz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValasz3ActionPerformed(evt);
            }
        });

        lstNyeremenySzintek.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lstNyeremenySzintek.setEnabled(false);
        lstNyeremenySzintek.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNyeremenySzintekValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstNyeremenySzintek);

        lbKerdes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbVagoIstvanKep, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnValasz0, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnValasz2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnValasz1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnValasz3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(lbKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnValasz0, btnValasz1, btnValasz2, btnValasz3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbVagoIstvanKep, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnValasz1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btnValasz0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnValasz2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnValasz3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnValasz0, btnValasz1, btnValasz2, btnValasz3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstNyeremenySzintekValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNyeremenySzintekValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstNyeremenySzintekValueChanged

    private void btnValasz0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz0ActionPerformed

        valaszVizsgal(0);
    }//GEN-LAST:event_btnValasz0ActionPerformed

    private void btnValasz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz1ActionPerformed
        valaszVizsgal(1);
    }//GEN-LAST:event_btnValasz1ActionPerformed

    private void btnValasz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz2ActionPerformed
        valaszVizsgal(2);
    }//GEN-LAST:event_btnValasz2ActionPerformed

    private void btnValasz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValasz3ActionPerformed
        valaszVizsgal(3);
    }//GEN-LAST:event_btnValasz3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Foablak().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Foablak.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValasz0;
    private javax.swing.JButton btnValasz1;
    private javax.swing.JButton btnValasz2;
    private javax.swing.JButton btnValasz3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbKerdes;
    private javax.swing.JLabel lbVagoIstvanKep;
    private javax.swing.JList<String> lstNyeremenySzintek;
    // End of variables declaration//GEN-END:variables
}
